[workspace]
members = [
    "apps/miner-cli",
    "core/config",
    "core/process",
    "core/logging",
    "core/watchdog",
    "core/mining",
    "core/stats",
    "core/scheduler",
    "core/devfee",
    "core/shares",
    "core/stratum",
    "algos/pearl",
    "backends/cpu",
    "integrations/pearlpool"
]
resolver = "2"
